# A) ForwardPropagation (Propagacion hacia delante)

En este erjercicio generaremos una propagacion hacia delante y posteriormente 
una propagacion hacia atras dentro de lamisma red de neuronas que se definira 
<!-- a continuacion. -->

Como paso preliminar preparamos el entorno donde trabajaremos

-   Instalamos las libreras que nos falten, en este caso faltaba por instalar PANDAS.
-   Importamos las librerias que usaremos.

In [181]:
#pip install pandas
#pip install matplotlib

In [182]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt  #para el BackPropagation


1.- Se define una red neuronal con las siguientes caracteristicas

-   1.- Una capa de entrada con dos inputs, x1 y x2.
-   2.- Una capa oculta con 4 neronas h1, h2 , h3 y h4.
-   3.-una capa de salida con 1 neurona o1.

2.- Inicializamos los pesos de las 4 neuronas de la capa oculta y los visualisamos

In [183]:
Wxh=np.array([[0.2,0.65,0.45,0.12],
              [0.8,0.35,0.55,0.15],
              ]) # X1 [1x4] y X2 [1x4]
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


3.- Inicializamos los pesos de las neuronas de la capa de salida 

In [184]:
#pesos de la neirona de la capa de salida

Why=np.array([[0.2],
              [0.35],
              [0.45],
              [0.52],
              ]) #Xo1 [4x1]
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


4.- Inicializamos los sesgos de la neuronas de la capa oculta Z1 y de la capa de salida Z2

In [198]:
bh=np.array([0.2,0.15,0.45,0.23]) #bh [1x4]
by=0.05 #by [1x4]
print(bh,by)

[0.2  0.15 0.45 0.23] 0.05


5.- Definimos la funcion de activacion como la sigmoide o logistic (logit)

In [186]:
def sigmoid(x):
  s=  1/(1+np.exp(-x))
  return s

6.- Definimos la propagacion hacia delante

In [199]:
def forward_prop(x):
    global z1, z2
    z1=np.dot(x,Wxh)+bh     #capa oculta -----(1x2)(2x4)=(1x4)+(1x4)
    a1=sigmoid(z1)          #capa oculta -----(1x4)
    z2=np.dot(a1,Why)+by    #capa salida -----(1x4)(4x1)=(1x1)
    y_gorro=sigmoid(z2)     #capa salida -----(1x4)
    return y_gorro          #salida -----(1x1)

7.- Definimos el vector de impulso para estimar y_Gorro 

In [200]:
#x=np.array([1.75,70])
#y_gorro = forward_prop(x)
#y_gorro 

array([0.8277821])

# B) Backpropagation (propagacion hacia atras)

1.- Definicion de la derivada de la sigmoide Prima

In [202]:
def sigmoidPrime(x):
 d  =  np.exp(-x)/((1+np.exp(-x))**2)
 return d

2.- Preparamos la BackPropagation

In [209]:
def backword_prop(y_gorro, z1, a1, z2, alpha):
    global Wxh, Why, dJ_dWxh
    delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2))  # --> 1x1 X 1x1 = 1x1
    dJ_dWxh = np.dot(a1.reshape(4,1), delta2) # --> 4x1.T * 1x1 = 4x1
    delta1 = np.dot(delta2,Why.T)*sigmoidPrime(z1)  # --> 1x1 * 1x4.T * 1 = 1x4
    dJ_dWhy = np.dot(x.reshape(2,1), delta1.reshape(1,4))  # --> 2x1 * 1x4 =2x4
    Wxh = Wxh - alpha * dJ_dWxh # -->4x1 -alpha * 4x1
    Why = Why - alpha * dJ_dWhy.reshape(1,8)  #4x1-alpha *  1x8.T = 
    return Wxh, Why

3.- Recalculo de parametros empleando BackPropagation

In [210]:
x = np.array([1.6,65.8])
y_gorro = forward_prop(x)
z1 = np.dot(x,Wxh) + bh
a1 = sigmoid(z1)
z2 = np.dot(a1,Why) + by
alpha = 0.025
y = 0.56

In [211]:
backword_prop(y_gorro, z1, a1, z2,alpha)

(array([[0.19617297, 0.64617297, 0.44617297, 0.11617313],
        [0.79617297, 0.34617297, 0.54617297, 0.14617313]]),
 array([[0.2       , 0.2       , 0.2       , 0.19999997, 0.2       ,
         0.2       , 0.2       , 0.19999866],
        [0.35      , 0.35      , 0.35      , 0.34999997, 0.35      ,
         0.35      , 0.35      , 0.34999866],
        [0.45      , 0.45      , 0.45      , 0.44999997, 0.45      ,
         0.45      , 0.45      , 0.44999866],
        [0.52      , 0.52      , 0.52      , 0.51999997, 0.52      ,
         0.52      , 0.52      , 0.51999866]]))

In [ ]:

#Definir fución de predicción.

def pred(X):
 z1 = np.dot(X,Wxh) + bh
 a1 = sigmoid(z1)
 z2 = np.dot(a1,Why) + by
 y_hat = sigmoid(z2)
 return y_hat