# Red Neuronal Propagación hacia delante


In [35]:
import pandas as pd 
import numpy as np


### Se define una RNA con las sig. características:

1. Una capa de entrada con dos inputs x1, x2
2. Una capa oculta con 4 neuronas h1, h2, h3 y h4
3. Una capa de salida con 1 neurona o1


#### Inicializar los pesos de las 4 neuronas de la capa oculta

In [36]:
# Se define una RNA con las sig. características
Wxh = np.array([[0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15] ,
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15]
                ])
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


#### Inicializar los pesos de la neurona en la capa de salida

In [37]:
Why = np.array([[0.2],  
                [0.35], 
                [0.45], 
                [0.52], 
                ])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


#### Inicializamos los sesgos

In [38]:
bh = np.array([0 ,0,0,0 ])
by = 0
print(bh,by)

[0 0 0 0] 0


#### Definir funcion de activacion

Como la sigmoide o la logit

In [39]:
def sigmoid(x):
  s= 1/(1 + np.exp(-x))
  return s

#### Definir la propagacion hacia delante 

In [45]:
def forward_prop(x):
  global z1,z2
  z1 = np.dot(x,Wxh) + bh   #capa oculta  -- (1x2) (2x4) = (1x4) --> (1x4)+(1x4) --> 1x4
  a1 = sigmoid(z1)          #capa oculta  -- (1x4)
  z2 = np.dot(a1, Why) + by #capa salida  -- (1x4) (4x1)
  y_gorro = sigmoid(z2)     #capa salida  -- (1x1) -- escalar
  
  return y_gorro 

# Back propagation

In [41]:
import matplotlib.pyplot as plt

#### Definicion de la derivada de la sigmoide

In [42]:
def sigmoidPrime(x):
  d = (np.exp(-x)) / ((1 + np.exp(-x))**2)
  return d

In [43]:
def back_prop(y_gorro, z1,a1,z2,y, alpha ):
  global Wxh, Why ,dJ_dWxh
  delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2)) # 1x1
  dJ_dWhy = np.dot(a1.reshape(4,1) , delta2) # 4 x 1 ) ( 1 x 1 ) 
  delta1= np.dot(delta2, Why.T)*sigmoidPrime(z1) # ( 4x1 ) 
  dJ_dWxh =np.dot(X.reshape(11,1) , delta1.reshape(1,4))
  Wxh = Wxh - alpha * dJ_dWxh
  Why =  Why  - alpha * dJ_dWhy.reshape(4,1)
  return Wxh, Why #Wxh 2 x 4 \\ Why 4x1

In [44]:
df = pd.read_excel("EarlyRetirementPrediction.xlsx")

df = df.reset_index()  # make sure indexes pair with number of rows

alpha= 0.025

for index, row in df.iterrows():
    X = np.array([row['Gender'],
                  row['Desease'],
                  row['Monthly Income'],
                  row['Dependants'],
                  row['Education Level'],
                  row['Marital Status'],
                  row['Employee/Employer'],
                  row['Unemployment Rate'],
                  row['Stock Market'],
                  row['Credit Score'],
                  row['Government Bonds Return']])
    y_gorro_gender = forward_prop(X)
    z1  = np.dot(X, Wxh) + bh
    a1 = sigmoid(z1)
    z2 = np.dot(a1, Why) + by
    back_prop(y_gorro, z1,a1,z2,row['Retire Before 65 Years Old'], alpha )

    
    

FileNotFoundError: [Errno 2] No such file or directory: 'EarlyRetirementPrediction.xlsx'

In [ ]:
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [ ]:
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [ ]:
#Primera observacion en el DF
x= df.iloc[1,2:].values
print(x)
print(df.iloc[1,1:].values)

NameError: name 'df' is not defined

In [ ]:
forward_prop(x)

array([0.02182991])