# Propagacion hacia delante

In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [10]:
import pandas as pd
import numpy as np

se define una red neuronal con las siguientes caracteristicas

-   1.- Una capa de entrada con dos inputs, x1, x2, x3 y x4
-   2.- Una capa oculta con 4 neronas h1, h2 , h3 y h4
-   3.-una capa de salida con 1 neurona o1

In [11]:
#inicializamos los pesos de las 4 neronas de la capa oculta
Wxh=np.array([[0.2,0.65,0.45,0.12],[0.8,0.35,0.55,0.15]])
print(Wxh)


[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [12]:
#pesos de la neirona de la capa de salida

Why=np.array([[0.2],[0.35],[0.45],[0.52]])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [16]:
#inicializamos los sesgos
bh=np.array([0.2,0.15,0.45,0.23])
print(bh)
by=0.5

[0.2  0.15 0.45 0.23]


In [14]:
#definimos la funcion de activacion como la sigmoide o logit
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [15]:
#definimos la propagacion hacia delante

def forward_prop(x):
    z1=np.dot(x,Wxh)+bh     #capa oculta -----(1x2)(2x4)=(1x4)+(1x4)
    a1=sigmoid(z1)          #capa oculta -----(1x4)
    z2=np.dot(a1,Why)+by    #capa salida -----(1x4)(4x1)=(1x1)
    y_gorro=sigmoid(z2)     #capa salida -----(1x4)
    return y_gorro

In [17]:
x=np.array([1.75,70])
y_gorro=forward_prop(x)
y_gorro 

array([0.88288006])

# Backpropagation

In [24]:
#Definir función sigmoide prima
def sigmoidPrime(x):
    return np.exp(-x)/((1+np.exp(-x))**2)

In [30]:
def backword_prop(y_gorro, z1, a1, z2, alpha):
    global Wxh, Why, y
    delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2))
    dJ_dWxh = np.dot(a1.T, delta2)
    delta1 = np.dot(delta2,Why.T)*sigmoidPrime(z1)
    dJ_dWhy= np.dot(x.T, delta1)
    Wxh = Wxh-alpha*dJ_dWxh
    Why = Why-alpha*dJ_dWhy
    return Wxh, Why

In [23]:
pip install matplotlib

                                              0.0/7.6 MB ? eta -:--:--
                                              0.0/7.6 MB 1.3 MB/s eta 0:00:06
                                              0.1/7.6 MB 1.6 MB/s eta 0:00:05
     -                                        0.2/7.6 MB 1.7 MB/s eta 0:00:05
     -                                        0.3/7.6 MB 2.3 MB/s eta 0:00:04
     --                                       0.5/7.6 MB 2.7 MB/s eta 0:00:03
     -----                                    1.0/7.6 MB 4.6 MB/s eta 0:00:02
     ------                                   1.3/7.6 MB 5.1 MB/s eta 0:00:02
     ---------                                1.9/7.6 MB 6.7 MB/s eta 0:00:01
     ------------                             2.4/7.6 MB 7.3 MB/s eta 0:00:01
     ---------------                          2.9/7.6 MB 8.0 MB/s eta 0:00:01
     ------------------                       3.5/7.6 MB 8.8 MB/s eta 0:00:01
     ---------------------                    4.1/7.6 MB 9.2 MB/s eta 0

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

X=x
y=1
#Definir función sigmoide
def sigmoid(x):
 return 1/ (1+np.exp(-x))

#Inicializar los pesos de las 3 neuronas de la capa oculta.

Wxh=np.array([[0.2,0.65,0.45,0.34],
             [0.8,0.35,0.55,0.21]])
print(Wxh)


#Inicializar pesos en la neurona de salida.

Why=np.array([[0.15],
             [0.3],
             [0.45],
             [0.1]])
print(Why)


#Inicializar sesgo de las neuronas en la capa oculta.

bh=np.array([[0.2,0.15,0.45,0.1]])

print(bh)


#Definir la forward propagation.

def forward_prop(X):
 z1 = np.dot(X,Wxh) + bh
 a1 = sigmoid(z1)
 z2 = np.dot(a1,Why) + by
 y_hat = sigmoid(z2)
 return y_hat


#Definir la back propagation.

def backword_prop(y_hat, z1, a1, z2,alpha):
 global Wxh, Why
 delta2 = np.multiply(-(y-y_hat),sigmoidPrime(z2))
 dJ_dWhy = np.dot(a1.T, delta2)
 delta1 = np.dot(delta2,Why.T)*sigmoidPrime(z1)
 dJ_dWxh = np.dot(X.T, delta1)
 Wxh = Wxh - alpha * dJ_dWxh
 Why = Why - alpha * dJ_dWhy
 return Wxh,Why


#Reecalcular parámetros
y_hat=forward_prop(X)
z1 = np.dot(X,Wxh) + bh
a1 = sigmoid(z1)
z2 = np.dot(a1,Why) + by
alpha=0.025

backword_prop(y_hat, z1, a1, z2,alpha)


#Definir fución de predicción.

def pred(X):
 z1 = np.dot(X,Wxh) + bh
 a1 = sigmoid(z1)
 z2 = np.dot(a1,Why) + by
 y_hat = sigmoid(z2)
 return y_hat

[[0.2  0.65 0.45 0.34]
 [0.8  0.35 0.55 0.21]]
[[0.15]
 [0.3 ]
 [0.45]
 [0.1 ]]
[[0.2  0.15 0.45 0.1 ]]


ValueError: shapes (2,) and (1,4) not aligned: 2 (dim 0) != 1 (dim 0)