# Propagacion hacia delante

In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [10]:
import pandas as pd
import numpy as np

se define una red neuronal con las siguientes caracteristicas

-   1.- Una capa de entrada con dos inputs, x1, x2, x3 y x4
-   2.- Una capa oculta con 4 neronas h1, h2 , h3 y h4
-   3.-una capa de salida con 1 neurona o1

In [11]:
#inicializamos los pesos de las 4 neronas de la capa oculta
Wxh=np.array([[0.2,0.65,0.45,0.12],[0.8,0.35,0.55,0.15]])
print(Wxh)


[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [12]:
#pesos de la neirona de la capa de salida

Why=np.array([[0.2],[0.35],[0.45],[0.52]])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [16]:
#inicializamos los sesgos
bh=np.array([0.2,0.15,0.45,0.23])
print(bh)
by=0.5

[0.2  0.15 0.45 0.23]


In [14]:
#definimos la funcion de activacion como la sigmoide o logit
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [15]:
#definimos la propagacion hacia delante

def forward_prop(x):
    z1=np.dot(x,Wxh)+bh     #capa oculta -----(1x2)(2x4)=(1x4)+(1x4)
    a1=sigmoid(z1)          #capa oculta -----(1x4)
    z2=np.dot(a1,Why)+by    #capa salida -----(1x4)(4x1)=(1x1)
    y_gorro=sigmoid(z2)     #capa salida -----(1x4)
    return y_gorro

In [17]:
x=np.array([1.75,70])
y_gorro=forward_prop(x)
y_gorro 

array([0.88288006])