# A) ForwardPropagation (Propagacion hacia delante)

En este erjercicio generaremos una propagacion hacia delante y posteriormente 
una propagacion hacia atras dentro de lamisma red de neuronas que se definira 
<!-- a continuacion. -->

Como paso preliminar preparamos el entorno donde trabajaremos

-   Instalamos las libreras que nos falten, en este caso faltaba por instalar PANDAS.
-   Importamos las librerias que usaremos.

In [60]:
#pip install pandas
#pip install matplotlib

In [61]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt  #para el BackPropagation


1.- Se define una red neuronal con las siguientes caracteristicas

-   1.- Una capa de entrada con dos inputs, x1 y x2.
-   2.- Una capa oculta con 4 neronas h1, h2 , h3 y h4.
-   3.-una capa de salida con 1 neurona o1.

2.- Inicializamos los pesos de las 4 neuronas de la capa oculta y los visualisamos

In [62]:
Wxh=np.array([[0.2,0.65,0.45,0.12],[0.8,0.35,0.55,0.15]]) # X1 [1x4] y X2 [1x4]
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


3.- Inicializamos los pesos de las neuronas de la capa de salida 

In [63]:
#pesos de la neirona de la capa de salida

Why=np.array([[0.2],[0.35],[0.45],[0.52]]) #Xo1 [4x1]
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


4.- Inicializamos los sesgos de la neuronas de la capa oculta Z1 y de la capa de salida Z2

In [64]:
bh=np.array([0.2,0.15,0.45,0.23]) #bh [1x4]
print(bh)
by=0.5 #by [1x4]
print(by)

[0.2  0.15 0.45 0.23]
0.5


5.- Definimos la funcion de activacion como la sigmoide o logistic (logit)

In [65]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

6.- Definimos la propagacion hacia delante

In [66]:
def forward_prop(x):
    z1=np.dot(x,Wxh)+bh     #capa oculta -----(1x2)(2x4)=(1x4)+(1x4)
    a1=sigmoid(z1)          #capa oculta -----(1x4)
    z2=np.dot(a1,Why)+by    #capa salida -----(1x4)(4x1)=(1x1)
    y_gorro=sigmoid(z2)     #capa salida -----(1x4)
    return y_gorro

7.- Definimos el vector de impulso para estimar y_Gorro 

In [67]:
x=np.array([1.75,70])
y_gorro=forward_prop(x)
y_gorro 

array([0.88288006])

# B) Backpropagation (propagacion hacia atras)

1.- Definicion de la derivada de la sigmoide Prima

In [68]:
def sigmoidPrime(x):
    return np.exp(-x)/((1+np.exp(-x))**2)

2.- Preparamos la BackPropagation

In [69]:
def backword_prop(y_gorro, z1, a1, z2, alpha):
    global Wxh, Why, y, dJ_dWxh
    delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2))  # --> 1x1 X 1x1 = 1x1
    dJ_dWxh = np.dot(a1.reshape(4,1), delta2) # --> 4x1.T * 1x1 = 4x1
    delta1 = np.dot(delta2,Why.T)*sigmoidPrime(z1)  # --> 1x1 * 1x4.T * 1 = 1x4
    dJ_dWhy = np.dot(X.reshape(2,1), delta1.reshape(1,4))  # --> 2x1 * 1x4 =2x4
    Wxh = Wxh-alpha*dJ_dWxh # -->4x1 -alpha * 4x1
    Why = Why - alpha * dJ_dWhy.T  #4x1-alpha *  1x8.T = 
    return Wxh, Why

3.- Recalculo de parametros empleando BackPropagation

In [70]:
X = np.array([1.9,63.8])
y_gorro=forward_prop(x)
z1 = np.dot(X,Wxh) + bh
a1 = sigmoid(z1)
z2 = np.dot(a1,Why) + by
alpha=0.025
y = 0.56

In [71]:
backword_prop(y_gorro, z1, a1, z2,alpha)

(array([[0.19916532, 0.64916532, 0.44916532, 0.11916536],
        [0.79916532, 0.34916532, 0.54916532, 0.14916536]]),
 array([[0.2       , 0.2       ],
        [0.35      , 0.35      ],
        [0.45      , 0.45      ],
        [0.51999996, 0.51999878]]))

In [72]:

#Definir fución de predicción.

def pred(X):
 z1 = np.dot(X,Wxh) + bh
 a1 = sigmoid(z1)
 z2 = np.dot(a1,Why) + by
 y_hat = sigmoid(z2)
 return y_hat

In [73]:
clear all