# Red Neuronal Propagación hacia delante 4 neronas ocultas 11 entradas


In [1]:
import pandas as pd 
import numpy as np

### Se define una RNA con las sig. características:

1. Una capa de entrada con dos inputs x1, x2
2. Una capa oculta con 4 neuronas h1, h2, h3 y h4
3. Una capa de salida con 1 neurona o1


#### Inicializar los pesos de las 4 neuronas de la capa oculta

In [2]:
# Se define una RNA con las sig. características
Wxh = np.array([[0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15] ,
                [0.8,0.35,0.55,0.15],
                [0.2,0.65, 0.45,0.12],
                [0.8,0.35,0.55,0.15]
                ])
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


#### Inicializar los pesos de la neurona en la capa de salida

In [3]:
Why = np.array([[0.2],  
                [0.35], 
                [0.45], 
                [0.52], 
                ])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


#### Inicializamos los sesgos

In [4]:
bh = np.array([0 ,0,0,0 ])
by = 0
print(bh,by)

[0 0 0 0] 0


#### Definir funcion de activacion

Como la sigmoide o la logit

In [5]:
def sigmoid(x):
  s= 1/(1 + np.exp(-x))
  return s

#### Definir la propagacion hacia delante 

In [6]:
def forward_prop(x):
  global z1,z2
  z1 = np.dot(x,Wxh)+bh   #capa oculta  -- (1x2) (2x4) = (1x4) --> (1x4)+(1x4) --> 1x4
  a1 = sigmoid(z1)          #capa oculta  -- (1x4)
  z2 = np.dot(a1, Why)+by #capa salida  -- (1x4) (4x1)
  y_gorro = sigmoid(z2)     #capa salida  -- (1x1) -- escalar
  return y_gorro 

# Back propagation

In [7]:
import matplotlib.pyplot as plt

#### Definicion de la derivada de la sigmoide

In [8]:
def sigmoidPrime(x):
  d = (np.exp(-x)) / ((1 + np.exp(-x))**2)
  return d

In [9]:
def back_prop(y_gorro, z1,a1,z2,y, alpha ):
  global Wxh, Why ,dJ_dWxh
  delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2)) # --> 1x1 X 1x1       = 1x1
  dJ_dWhy = np.dot(a1.reshape(4,1) , delta2)           # --> 4x1.T * 1x1     = 4x1 
  delta1= np.dot(delta2, Why.T)*sigmoidPrime(z1)       # --> 1x1 * 1x4.T * 1 = 1x4
  dJ_dWxh =np.dot(X.reshape(11,1) , delta1.reshape(1,4)) # --> 11x1 * 1x4    = 11x4
  Wxh = Wxh - alpha * dJ_dWxh                          # --> 4x1 -alpha * 11x4 =
  Why =  Why  - alpha * dJ_dWhy.reshape(4,1)
  return Wxh, Why #Wxh 2 x 4 \\ Why 4x1

In [10]:
df = pd.read_csv("EarlyRetirementPrediction.csv")
df

Retire Before 65 Years Old  Gender  Desease  Education Level   
0                              1       1        1                3  \
1                              0       1        0                3   
2                              0       1        1                4   
3                              0       0        1                4   
4                              0       0        1                3   
...                          ...     ...      ...              ...   
1495                           1       0        0                5   
1496                           0       1        0                3   
1497                           1       1        1                4   
1498                           0       0        0                5   
1499                           0       0        1                3   

      Marital Status  Monthly Income  Employee/Employer  Dependants   
0                  0           18000                  0           4  \
1                  0           32000                  0           1   
2                  0           20000                  0           2   
3                  1           35000                  1           1   
4                  0           27000                  0           1   
...              ...             ...                ...         ...   
1495               1           26000                  0           2   
1496               0           32000                  0           4   
1497               1           17000                  0           2   
1498               0           26000                  0           2   
1499               1           33000                  1           1   

      Unemployment Rate  Stock Market  Credit Score  Government Bonds Return  
0              3.444876   24066.16667           699                 7.715833  
1              5.023797   42063.16667           639                 5.414833  
2              5.355220   30100.50000           610                 7.962750  
3              3.843570   24066.16667           649                 7.715833  
4              4.949226   19439.00000           638                 8.024167  
...                 ...           ...           ...                      ...  
1495           5.111358   32304.66667           604                 7.193917  
1496           4.929185   41229.83333           753                 5.910000  
1497           5.054852   37846.16667           631                 6.198750  
1498           4.827790   41229.83333           613                 5.910000  
1499           5.195010   31577.33333           649                 7.701083  

[1500 rows x 12 columns]

In [11]:

df = df.reset_index()  # make sure indexes pair with number of rows

alpha= 0.025

for index, row in df.iterrows():
    X = np.array([row['Gender'],
                  row['Desease'],
                  row['Monthly Income'],
                  row['Dependants'],
                  row['Education Level'],
                  row['Marital Status'],
                  row['Employee/Employer'],
                  row['Unemployment Rate'],
                  row['Stock Market'],
                  row['Credit Score'],
                  row['Government Bonds Return']])
    y_gorro_gender = forward_prop(X)
    z1  = np.dot(X, Wxh) + bh
    a1 = sigmoid(z1)
    z2 = np.dot(a1, Why) + by
    back_prop(y_gorro_gender, z1,a1,z2,row['Retire Before 65 Years Old'], alpha )
#row['Retire Before 65 Years  = y    

In [12]:
y_gorro_gender

array([0.48776092])

In [13]:
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]
 [0.8  0.35 0.55 0.15]
 [0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [14]:
print(Why)

[[-0.1952882]
 [-0.0452882]
 [ 0.0547118]
 [ 0.1247118]]


llamamos al 

In [15]:
l = df.iloc[1,2:].values
l

array([1.00000000e+00, 0.00000000e+00, 3.00000000e+00, 0.00000000e+00,
       3.20000000e+04, 0.00000000e+00, 1.00000000e+00, 5.02379729e+00,
       4.20631667e+04, 6.39000000e+02, 5.41483333e+00])

In [16]:
forward_prop(l)  #0.02182 

array([0.48471656])