In [23]:
import numpy as np
import pandas as pd

## 1.- inportamos los datos

In [24]:
BaseAumentada = pd.read_csv("BaseLD.csv", header=0, sep=",")

In [40]:
BaseAumentada

SegmentR  PEPR  AgeR  TimeRelationR  IncomeSourceR  ActivityR   
0            80   100    96            100            100         97  \
1            96    96    97             98             99         96   
2            81    98    99             99             99         98   
3            96    99    99            100             96         99   
4            82    99    98             98             97        100   
...         ...   ...   ...            ...            ...        ...   
27746        19    12    32             19             27         19   
27747        20     9    32             18             25         19   
27748        22    10    34             21             26         19   
27749        20    12    33             20             24         22   
27750        20    11    34             21             26         19   

       NationalityR  CommonAddR  ProductTR  SubproductR  ...  SumReR  RSR   
0                96          72         98           77  ...      64   66  \
1                96          69         97           77  ...      83   84   
2                97          68         96           98  ...      84   64   
3                99          68         98           99  ...      84   84   
4                97          68        100           96  ...      66   84   
...             ...         ...        ...          ...  ...     ...  ...   
27746            11          11         26            8  ...      25   23   
27747            10          10         27           12  ...      26   27   
27748             8          10         26            3  ...      24    5   
27749             9          11         23            6  ...      24   27   
27750             9           8         27           11  ...       3   27   

       AAR  SendingNumR  ReceivingNumR  StateOpeR  StateResR  MunOpeR   
0       72           80             78         91         79       97  \
1       71           81             78         92         81       99   
2       89           82             82         90         82       99   
3       88           81             80         91         82       96   
4       68           80             82         89         82       97   
...    ...          ...            ...        ...        ...      ...   
27746   29            4              6         19         19       17   
27747   12           21             20         18         22       16   
27748   28           18              6         29         20       15   
27749   12           20             18         28          9       14   
27750    8            5             21         22         18       16   

       MunResR  CountryR  
0           89        99  
1           90       100  
2           92        96  
3           89        96  
4           89        97  
...        ...       ...  
27746        4        10  
27747        5         9  
27748        7         8  
27749        5        12  
27750        7         8  

[27751 rows x 30 columns]

## 2.- Algoritmo

In [25]:

pertenencia=np.zeros((27751, 1))

m=BaseAumentada.shape[0]
n =BaseAumentada.shape[1]
colnames = BaseAumentada.columns
neuronas =np.zeros((3, n))
promedio =np.zeros((1, n))
minimo =np.zeros((1, n))
maximo =np.zeros((1, n))

In [26]:
maximo

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 3.- Inicializacion de ubicaciones

In [27]:

for i in range(n):
    minimo[0, i] = BaseAumentada.iloc[:, i].min()

for i in range(n):
    maximo[0, i] = BaseAumentada.iloc[:, i].max()

for i in range(n):
    promedio[0, i] = BaseAumentada.iloc[:, i].mean()

neuronas[0, :] = minimo[0, :]
neuronas[1, :] = promedio[0, :]
neuronas[2, :] = maximo[0, :]

## 4.- Synaptic potencial

In [28]:

h = np.zeros((1, 3))
base = BaseAumentada.to_numpy()

## 5.- Cluster

In [29]:

for k in range(3):
    cluster = np.zeros((1, 3))
    for i in range(m):
        for j in range(3):
            h[:, j] = base[i, :].dot(neuronas[j, :]) - 0.5 * (neuronas[j, :].dot(neuronas[j, :]))
        un = 0.5 * (1 - i / m)
        max_h = max(h[:, 0], h[:, 1], h[:, 2])
        if h[:, 0] == max_h:
            neuronas[0, :] += un * (base[i, :] - neuronas[0, :])
            cluster[:, 0] += 1
            pertenencia[i] = 1
        if h[:, 1] == max_h:
            neuronas[1, :] += un * (base[i, :] - neuronas[1, :])
            cluster[:, 1] += 1
            pertenencia[i] = 2
        if h[:, 2] == max_h:
            neuronas[2, :] += un * (base[i, :] - neuronas[2, :])
            cluster[:, 2] += 1
            pertenencia[i] = 3
    k += 1

In [30]:
neuronas

array([[44.30039262, 10.03970647, 45.66173073, 35.96714233, 44.07835104,
        35.15987177, 10.04094374,  9.8971198 , 24.94352227, 32.43604532,
         4.07015728, 51.58543971, 34.39679459, 31.21704237, 46.7470065 ,
        10.10452368, 14.75724206, 31.35505115, 30.49590065, 15.16731852,
        14.45993839, 14.67827544, 20.73936654, 12.64209121, 11.62726666,
        24.8416892 , 28.72002146, 15.05907823,  4.92397147,  9.98343582],
       [19.9771961 ,  9.88629341, 33.08716638, 19.98022794, 25.04151194,
        19.93382217,  9.81563871, 10.0561871 , 24.88809569,  7.457917  ,
         4.05749562, 19.89016335, 19.94497686, 19.90636542, 11.09551768,
        10.13701346, 15.42654205, 29.72210538, 31.61217563, 14.70483149,
        13.00359421, 14.97051035, 18.84139956, 13.09422725, 12.19221475,
        24.89212918, 15.11796559, 15.1602735 ,  4.88553038,  9.98273905],
       [74.71351763, 83.8059132 , 93.52798447, 97.97071226, 97.64740112,
        77.16430213, 41.52009921, 10.43884764, 33

In [31]:
cluster.sum()

27751.0

In [32]:
cluster

array([[  199., 13962., 13590.]])

In [33]:
pd.Series(pertenencia).value_counts()

ValueError: Data must be 1-dimensional, got ndarray of shape (27751, 1) instead

# K-Means

# STEP 2. ALGORITHM.

In [34]:

pertenencia=np.zeros((27751, 1))

m=BaseAumentada.shape[0]
n =BaseAumentada.shape[1]
colnames = BaseAumentada.columns
neuronas =np.zeros((3, n))
promedio =np.zeros((1, n))
minimo =np.zeros((1, n))
maximo =np.zeros((1, n))

# Initialize the locations.

In [35]:

for i in range(n):
    minimo[0, i] = np.min(BaseAumentada.iloc[:, i])

for i in range(n):
    maximo[0, i] = np.max(BaseAumentada.iloc[:, i])

for i in range(n):
    promedio[0, i] = np.mean(BaseAumentada.iloc[:, i])

neuronas[0, :] = minimo[0, :]
neuronas[1, :] = promedio[0, :]
neuronas[2, :] = maximo[0, :]

# Synaptic Potential

In [36]:
h = np.zeros((1, 3))
base = BaseAumentada.values
accum = np.zeros((3,n))

# Cluster

In [37]:
cluster = np.zeros((1, 3))

for k in range(3):
    cluster = np.zeros((1, 3))

    for i in range(m):
        for j in range(3):
            h[0, j] = np.dot(base[i, :], neuronas[j, :]) - 0.5 * (np.dot(neuronas[j, :], neuronas[j, :]))

        un = 0.5 * (1 - i / m)
        max_val = np.max(h[0, :])

        if h[0, 0] == max_val:
            neuronas[0, :] = neuronas[0, :]  #+ un * (base[i, :] - neuronas[0, :])
            cluster[0, 0] += 1
            pertenencia[i] = 1
            accum[0,:] =(accum[0,:] +  base[i, :]) / cluster[0,0]
            

        if h[0, 1] == max_val:
            neuronas[1, :] = neuronas[1, :]# + un * (base[i, :] - neuronas[1, :])
            cluster[0, 1] += 1
            pertenencia[i] = 2
            accum[1,:] = (accum[1,:] +  base[i, :]) / cluster[0,1]

        if h[0, 2] == max_val:
            neuronas[2, :] = neuronas[2, :] # + un * (base[i, :] - neuronas[2, :])
            cluster[0, 2] += 1
            pertenencia[i] = 3
            accum[2,:] =(accum[2,:] +  base[i, :]) / cluster[0,2]

    k += 1


In [38]:
cluster

array([[13793., 10845.,  3113.]])

In [39]:
cluster.sum()

27751.0

# Neural Gas

# STEP 2. ALGORITHM.

In [45]:
m = BaseAumentada.shape[0]
n = BaseAumentada.shape[1]
pertenencia = np.zeros(m)
neuronas = np.zeros((3, n))
promedio = np.zeros((1, n))
minimo = np.zeros((1, n))
maximo = np.zeros((1, n))

# Initialize the locations.

In [44]:
for i in range(n):
    minimo[0, i] = np.min(BaseAumentada.iloc[:, i])

for i in range(n):
    maximo[0, i] = np.max(BaseAumentada.iloc[:, i])

for i in range(n):
    promedio[0, i] = np.mean(BaseAumentada.iloc[:, i])

neuronas[0, :] = minimo[0, :]
neuronas[1, :] = promedio[0, :]
neuronas[2, :] = maximo[0, :]

# Synaptic Potential

In [42]:
h = np.zeros((1, 3))
base = BaseAumentada.values

In [49]:
t = 0
e0 = 0.3
ef = 0.05
lam0 = 10
lamf = 0.01
tmax = m

In [50]:
e = (e0*((ef/e0)**(i/tmax)))
lam = (lam0*((lamf/lam0)**(i/tmax)))

# Cluster

In [ ]:
cluster = np.zeros((1, 3))

for k in range(3):
    cluster = np.zeros((1, 3))

    for i in range(m):
        for j in range(3):
            h[0, j] = np.dot(base[i, :], neuronas[j, :]) - 0.5 * (np.dot(neuronas[j, :], neuronas[j, :]))

        un = 0.5 * (1 - i / m)
        max_val = np.max(h[0, :])

        if h[0, 0] == max_val:
            neuronas[0, :] = neuronas[0, :] + un * (base[i, :] - neuronas[0, :])
            cluster[0, 0] += 1
            pertenencia[i] = 1
            

        if h[0, 1] == max_val:
            neuronas[1, :] = neuronas[1, :] + un * (base[i, :] - neuronas[1, :])
            cluster[0, 1] += 1
            pertenencia[i] = 2

        if h[0, 2] == max_val:
            neuronas[2, :] = neuronas[2, :] + un * (base[i, :] - neuronas[2, :])
            cluster[0, 2] += 1
            pertenencia[i] = 3

    k += 1


